const DOMAIN_TREE = {
  "chim": { label: "Chimie", children: {
    "chim.othe": "Autre",
    "chim.cata": "Catalyse",
    "chim.chem": "Chemo-informatique",
    "chim.anal": "Chimie analytique",
    "chim.coor": "Chimie de coordination",
    "chim.inor": "Chimie inorganique",
    "chim.orga": "Chimie organique",
    "chim.theo": "Chimie théorique et/ou physique",
    "chim.ther": "Chimie thérapeutique",
    "chim.cris": "Cristallographie",
    "chim.geni": "Génie chimique",
    "chim.mate": "Matériaux",
    "chim.poly": "Polymères",
    "chim.radio": "Radiochimie",
  }},
  "info": { label: "Informatique [cs]", children: {
    "info.info-ds": "Algorithme et structure de données [cs.DS]",
    "info.info-na": "Analyse numérique [cs.NA]",
    "info.info-lg": "Apprentissage [cs.LG]",
    "info.info-ar": "Architectures Matérielles [cs.AR]",
    "info.info-ao": "Arithmétique des ordinateurs",
    "info.info-au": "Automatique",
    "info.info-oh": "Autre [cs.OH]",
    "info.info-db": "Base de données [cs.DB]",
    "info.info-dl": "Bibliothèque électronique [cs.DL]",
    "info.info-bi": "Bio-informatique [q-bio.QM]",
    "info.info-bt": "Biotechnologie",
    "info.info-sc": "Calcul formel [cs.SC]",
    "info.info-dc": "Calcul parallèle, distribué et partagé [cs.DC]",
    "info.info-cc": "Complexité [cs.CC]",
    "info.info-cr": "Cryptographie et sécurité [cs.CR]",
    "info.eiah": "Environnements Informatiques pour l'Apprentissage Humain",
    "info.info-se": "Génie logiciel [cs.SE]",
    "info.info-cg": "Géométrie algorithmique [cs.CG]",
    "info.info-im": "Imagerie médicale",
    "info.info-cl": "Informatique et langage [cs.CL]",
    "info.info-gt": "Informatique et théorie des jeux [cs.GT]",
    "info.info-mc": "Informatique mobile",
    "info.info-iu": "Informatique ubiquitaire",
    "info.info-ia": "Ingénierie assistée par ordinateur",
    "info.info-ce": "Ingénierie, finance et science [cs.CE]",
    "info.info-ai": "Intelligence artificielle [cs.AI]",
    "info.info-hc": "Interface homme-machine [cs.HC]",
    "info.info-pl": "Langage de programmation [cs.PL]",
    "info.info-gl": "Littérature générale [cs.GL]",
    "info.info-ms": "Logiciel mathématique [cs.MS]",
    "info.info-lo": "Logique en informatique [cs.LO]",
    "info.info-dm": "Mathématique discrète [cs.DM]",
    "info.info-mo": "Modélisation et simulation",
    "info.info-mm": "Multimédia [cs.MM]",
    "info.info-cy": "Ordinateur et société [cs.CY]",
    "info.info-pf": "Performance et fiabilité [cs.PF]",
    "info.info-ir": "Recherche d'information [cs.IR]",
    "info.info-ro": "Recherche opérationnelle [math.OC]",
    "info.info-rb": "Robotique [cs.RO]",
    "info.info-ne": "Réseau de neurones [cs.NE]",
    "info.info-ni": "Réseaux et télécommunications [cs.NI]",
    "info.info-si": "Réseaux sociaux et d'information [cs.SI]",
    "info.info-sd": "Son [cs.SD]",
    "info.info-gr": "Synthèse d'image et réalité virtuelle [cs.GR]",
    "info.info-os": "Système d'exploitation [cs.OS]",
    "info.info-ma": "Système multi-agents [cs.MA]",
    "info.info-es": "Systèmes embarqués",
    "info.info-sy": "Systèmes et contrôle [cs.SY]",
    "info.info-et": "Technologies Émergeantes [cs.ET]",
    "info.info-it": "Théorie de l'information [cs.IT]",
    "info.info-fl": "Théorie et langage formel [cs.FL]",
    "info.info-ti": "Traitement des images [eess.IV]",
    "info.info-ts": "Traitement du signal et de l'image [eess.SP]",
    "info.info-tt": "Traitement du texte et du document",
    "info.info-cv": "Vision par ordinateur et reconnaissance de formes [cs.CV]",
    "info.info-wb": "Web",
  }},
  "math": { label: "Mathématiques [math]", children: {
    "math.math-ac": "Algèbre commutative [math.AC]",
    "math.math-oa": "Algèbres d'opérateurs [math.OA]",
    "math.math-qa": "Algèbres quantiques [math.QA]",
    "math.math-ca": "Analyse classique [math.CA]",
    "math.math-fa": "Analyse fonctionnelle [math.FA]",
    "math.math-na": "Analyse numérique [math.NA]",
    "math.math-ra": "Anneaux et algèbres [math.RA]",
    "math.math-ct": "Catégories et ensembles [math.CT]",
    "math.math-co": "Combinatoire [math.CO]",
    "math.math-ap": "Equations aux dérivées partielles [math.AP]",
    "math.math-ag": "Géométrie algébrique [math.AG]",
    "math.math-dg": "Géométrie différentielle [math.DG]",
    "math.math-mg": "Géométrie métrique [math.MG]",
    "math.math-sg": "Géométrie symplectique [math.SG]",
    "math.math-ho": "Histoire et perspectives sur les mathématiques [math.HO]",
    "math.math-kt": "K-théorie et homologie [math.KT]",
    "math.math-lo": "Logique [math.LO]",
    "math.math-gm": "Mathématiques générales [math.GM]",
    "math.math-oc": "Optimisation et contrôle [math.OC]",
    "math.math-mp": "Physique mathématique [math-ph]",
    "math.math-pr": "Probabilités [math.PR]",
    "math.math-st": "Statistiques [math.ST]",
    "math.math-ds": "Systèmes dynamiques [math.DS]",
    "math.math-it": "Théorie de l'information et codage [math.IT]",
    "math.math-gr": "Théorie des groupes [math.GR]",
    "math.math-nt": "Théorie des nombres [math.NT]",
    "math.math-rt": "Théorie des représentations [math.RT]",
    "math.math-sp": "Théorie spectrale [math.SP]",
    "math.math-at": "Topologie algébrique [math.AT]",
    "math.math-gn": "Topologie générale [math.GN]",
    "math.math-gt": "Topologie géométrique [math.GT]",
    "math.math-cv": "Variables complexes [math.CV]",
  }},
  "nlin": { label: "Science non linéaire [physics]", children: {
    "nlin.nlin-ao": "Adaptation et Systèmes auto-organisés [nlin.AO]",
    "nlin.nlin-cg": "Automates cellulaires et gaz sur réseau [nlin.CG]",
    "nlin.nlin-cd": "Dynamique Chaotique [nlin.CD]",
    "nlin.nlin-ps": "Formation de Structures et Solitons [nlin.PS]",
    "nlin.nlin-si": "Systèmes Solubles et Intégrables [nlin.SI]",
  }},
  "phys": { label: "Physique [physics]", children: {
    "phys.hist": "Articles anciens",
    "phys.astr": "Astrophysique [astro-ph]",
    "phys.astr.ga": "Astrophysique [astro-ph]/Astrophysique galactique [astro-ph.GA]",
    "phys.astr.sr": "Astrophysique [astro-ph]/Astrophysique stellaire et solaire [astro-ph.SR]",
    "phys.astr.co": "Astrophysique [astro-ph]/Cosmologie et astrophysique extra-galactique [astro-ph.CO]",
    "phys.astr.im": "Astrophysique [astro-ph]/Instrumentation et méthodes pour l'astrophysique [astro-ph.IM]",
    "phys.astr.he": "Astrophysique [astro-ph]/Phénomènes cosmiques de haute energie [astro-ph.HE]",
    "phys.astr.ep": "Astrophysique [astro-ph]/Planétologie et astrophysique de la terre [astro-ph.EP]",
    "phys.cond": "Matière Condensée [cond-mat]",
    "phys.cond.cm-gen": "Matière Condensée [cond-mat]/Autre [cond-mat.other]",
    "phys.cond.cm-sce": "Matière Condensée [cond-mat]/Electrons fortement corrélés [cond-mat.str-el]",
    "phys.cond.gas": "Matière Condensée [cond-mat]/Gaz Quantiques [cond-mat.quant-gas]",
    "phys.cond.cm-scm": "Matière Condensée [cond-mat]/Matière Molle [cond-mat.soft]",
    "phys.cond.cm-sm": "Matière Condensée [cond-mat]/Mécanique statistique [cond-mat.stat-mech]",
    "phys.cond.cm-ms": "Matière Condensée [cond-mat]/Science des matériaux [cond-mat.mtrl-sci]",
    "phys.cond.cm-s": "Matière Condensée [cond-mat]/Supraconductivité [cond-mat.supr-con]",
    "phys.cond.cm-ds-nn": "Matière Condensée [cond-mat]/Systèmes désordonnés et réseaux de neurones [cond-mat.dis-nn]",
    "phys.cond.cm-msqhe": "Matière Condensée [cond-mat]/Systèmes mésoscopiques et effet Hall quantique [cond-mat.mes-hall]",
    "phys.meca": "Mécanique [physics]",
    "phys.meca.acou": "Mécanique [physics]/Acoustique [physics.class-ph]",
    "phys.meca.biom": "Mécanique [physics]/Biomécanique [physics.med-ph]",
    "phys.meca.geme": "Mécanique [physics]/Génie mécanique [physics.class-ph]",
    "phys.meca.msmeca": "Mécanique [physics]/Matériaux et structures en mécanique [physics.class-ph]",
    "phys.meca.mefl": "Mécanique [physics]/Mécanique des fluides [physics.class-ph]",
    "phys.meca.mema": "Mécanique [physics]/Mécanique des matériaux [physics.class-ph]",
    "phys.meca.solid": "Mécanique [physics]/Mécanique des solides [physics.class-ph]",
    "phys.meca.stru": "Mécanique [physics]/Mécanique des structures [physics.class-ph]",
    "phys.meca.ther": "Mécanique [physics]/Thermique [physics.class-ph]",
    "phys.meca.vibr": "Mécanique [physics]/Vibrations [physics.class-ph]",
    "phys.nexp": "Physique Nucléaire Expérimentale [nucl-ex]",
    "phys.nucl": "Physique Nucléaire Théorique [nucl-th]",
    "phys.qphy": "Physique Quantique [quant-ph]",
    "phys.phys": "Physique [physics]",
    "phys.phys.phys-atm-ph": "Physique [physics]/Agrégats Moléculaires et Atomiques [physics.atm-clus]",
    "phys.phys.phys-data-an": "Physique [physics]/Analyse de données, Statistiques et Probabilités [physics.data-an]",
    "phys.phys.phys-bio-ph": "Physique [physics]/Biophysique [physics.bio-ph]",
    "phys.phys.phys-chem-ph": "Physique [physics]/Chimie-Physique [physics.chem-ph]",
    "phys.phys.phys-flu-dyn": "Physique [physics]/Dynamique des Fluides [physics.flu-dyn]",
    "phys.phys.phys-ed-ph": "Physique [physics]/Enseignement de la physique [physics.ed-ph]",
    "phys.phys.phys-geo-ph": "Physique [physics]/Géophysique [physics.geo-ph]",
    "phys.phys.phys-hist-ph": "Physique [physics]/Histoire de la Physique [physics.hist-ph]",
    "phys.phys.phys-ins-det": "Physique [physics]/Instrumentations et Détecteurs [physics.ins-det]",
    "phys.phys.phys-optics": "Physique [physics]/Optique [physics.optics]",
    "phys.phys.phys-pop-ph": "Physique [physics]/Physique : vulgarisation [physics.pop-ph]",
    "phys.phys.phys-ao-ph": "Physique [physics]/Physique Atmosphérique et Océanique [physics.ao-ph]",
    "phys.phys.phys-atom-ph": "Physique [physics]/Physique Atomique [physics.atom-ph]",
    "phys.phys.phys-class-ph": "Physique [physics]/Physique Classique [physics.class-ph]",
    "phys.phys.phys-gen-ph": "Physique [physics]/Physique Générale [physics.gen-ph]",
    "phys.phys.phys-med-ph": "Physique [physics]/Physique Médicale [physics.med-ph]",
    "phys.phys.phys-comp-ph": "Physique [physics]/Physique Numérique [physics.comp-ph]",
    "phys.phys.phys-space-ph": "Physique [physics]/Physique de l'espace [physics.space-ph]",
    "phys.phys.phys-acc-ph": "Physique [physics]/Physique des accélérateurs [physics.acc-ph]",
    "phys.phys.phys-plasm-ph": "Physique [physics]/Physique des plasmas [physics.plasm-ph]",
    "phys.phys.phys-soc-ph": "Physique [physics]/Physique et Société [physics.soc-ph]",
    "phys.hexp": "Physique des Hautes Energies - Expérience [hep-ex]",
    "phys.hphe": "Physique des Hautes Energies - Phénoménologie [hep-ph]",
    "phys.hlat": "Physique des Hautes Energies - Réseau [hep-lat]",
    "phys.hthe": "Physique des Hautes Energies - Théorie [hep-th]",
    "phys.mphy": "Physique mathématique [math-ph]",
    "phys.grqc": "Relativité Générale et Cosmologie Quantique [gr-qc]",
  }},
  "qfin": { label: "Économie et finance quantitative [q-fin]", children: {
    "qfin.st": "Econométrie de la finance [q-fin.ST]",
    "qfin.gn": "Finance [q-fin.GN]",
    "qfin.cp": "Finance quantitative [q-fin.CP]",
    "qfin.pm": "Gestion de portefeuilles [q-fin.PM]",
    "qfin.rm": "Gestion des risques [q-fin.RM]",
    "qfin.tr": "Microstructure des marchés [q-fin.TR]",
    "qfin.pr": "Pricing [q-fin.PR]",
  }},
  "scco": { label: "Sciences cognitives", children: {
    "scco.comp": "Informatique",
    "scco.ling": "Linguistique",
    "scco.neur": "Neurosciences",
    "scco.psyc": "Psychologie",
  }},
  "sde": { label: "Sciences de l'environnement", children: {
    "sde.be": "Biodiversité et Ecologie",
    "sde.be.bp": "Biodiversité et Ecologie/domain_sde.be.bp",
    "sde.be.eco": "Biodiversité et Ecologie/domain_sde.be.eco",
    "sde.be.evo": "Biodiversité et Ecologie/domain_sde.be.evo",
    "sde.be.gp": "Biodiversité et Ecologie/domain_sde.be.gp",
    "sde.es": "Environnement et Société",
    "sde.ie": "Ingénierie de l'environnement",
    "sde.mcg": "Milieux et Changements globaux",
    "sde.mcg.cg": "Milieux et Changements globaux/domain_sde.mcg.cg",
    "sde.mcg.cpe": "Milieux et Changements globaux/domain_sde.mcg.cpe",
    "sde.mcg.sic": "Milieux et Changements globaux/domain_sde.mcg.sic",
  }},
  "sdu": { label: "Planète et Univers [physics]", children: {
    "sdu.astr": "Astrophysique [astro-ph]",
    "sdu.astr.ga": "Astrophysique [astro-ph]/Astrophysique galactique [astro-ph.GA]",
    "sdu.astr.sr": "Astrophysique [astro-ph]/Astrophysique stellaire et solaire [astro-ph.SR]",
    "sdu.astr.co": "Astrophysique [astro-ph]/Cosmologie et astrophysique extra-galactique [astro-ph.CO]",
    "sdu.astr.im": "Astrophysique [astro-ph]/Instrumentation et méthodes pour l'astrophysique [astro-ph.IM]",
    "sdu.astr.he": "Astrophysique [astro-ph]/Phénomènes cosmiques de haute energie [astro-ph.HE]",
    "sdu.astr.ep": "Astrophysique [astro-ph]/Planétologie et astrophysique de la terre [astro-ph.EP]",
    "sdu.other": "Autre",
    "sdu.envi": "Interfaces continentales, environnement",
    "sdu.ocean": "Océan, Atmosphère",
    "sdu.stu": "Sciences de la Terre",
    "sdu.stu.cl": "Sciences de la Terre/Climatologie",
    "sdu.stu.gl": "Sciences de la Terre/Glaciologie",
    "sdu.stu.gc": "Sciences de la Terre/Géochimie",
    "sdu.stu.ag": "Sciences de la Terre/Géologie appliquée",
    "sdu.stu.gm": "Sciences de la Terre/Géomorphologie",
    "sdu.stu.gp": "Sciences de la Terre/Géophysique [physics.geo-ph]",
    "sdu.stu.hy": "Sciences de la Terre/Hydrologie",
    "sdu.stu.mi": "Sciences de la Terre/Minéralogie",
    "sdu.stu.me": "Sciences de la Terre/Météorologie",
    "sdu.stu.oc": "Sciences de la Terre/Océanographie",
    "sdu.stu.pg": "Sciences de la Terre/Paléontologie",
    "sdu.stu.pl": "Sciences de la Terre/Planétologie",
    "sdu.stu.pe": "Sciences de la Terre/Pétrographie",
    "sdu.stu.st": "Sciences de la Terre/Stratigraphie",
    "sdu.stu.te": "Sciences de la Terre/Tectonique",
    "sdu.stu.vo": "Sciences de la Terre/Volcanologie",
  }},
  "sdv": { label: "Sciences du Vivant [q-bio]", children: {
    "sdv.aen": "Alimentation et Nutrition",
    "sdv.aen.nut": "Alimentation et Nutrition/domain_sdv.aen.nut",
    "sdv.ot": "Autre [q-bio.OT]",
    "sdv.bibs": "Bio-Informatique, Biologie Systémique [q-bio.QM]",
    "sdv.bbm": "Biochimie, Biologie Moléculaire",
    "sdv.bbm.bc": "Biochimie, Biologie Moléculaire/Biochimie [q-bio.BM]",
    "sdv.bbm.bm": "Biochimie, Biologie Moléculaire/Biologie moléculaire",
    "sdv.bbm.bs": "Biochimie, Biologie Moléculaire/Biologie structurale [q-bio.BM]",
    "sdv.bbm.bp": "Biochimie, Biologie Moléculaire/Biophysique",
    "sdv.bbm.gtp": "Biochimie, Biologie Moléculaire/Génomique, Transcriptomique et Protéomique [q-bio.GN]",
    "sdv.bbm.mn": "Biochimie, Biologie Moléculaire/Réseaux moléculaires [q-bio.MN]",
    "sdv.bid": "Biodiversité",
    "sdv.bid.evo": "Biodiversité/Evolution [q-bio.PE]",
    "sdv.bid.spt": "Biodiversité/Systématique, phylogénie et taxonomie",
    "sdv.ba": "Biologie animale",
    "sdv.ba.mvsa": "Biologie animale/Médecine vétérinaire et santé animale",
    "sdv.ba.zi": "Biologie animale/Zoologie des invertébrés",
    "sdv.ba.zv": "Biologie animale/Zoologie des vertébrés",
    "sdv.bc": "Biologie cellulaire",
    "sdv.bc.ic": "Biologie cellulaire/Interactions cellulaires [q-bio.CB]",
    "sdv.bc.bc": "Biologie cellulaire/Organisation et fonctions cellulaires [q-bio.SC]",
    "sdv.bdlr": "Biologie de la reproduction",
    "sdv.bdlr.ra": "Biologie de la reproduction/Reproduction asexuée",
    "sdv.bdlr.rs": "Biologie de la reproduction/Reproduction sexuée",
    "sdv.bdd": "Biologie du développement",
    "sdv.bdd.eo": "Biologie du développement/Embryologie et organogenèse",
    "sdv.bdd.gam": "Biologie du développement/Gamétogenèse",
    "sdv.bdd.mor": "Biologie du développement/Morphogenèse",
    "sdv.bv": "Biologie végétale",
    "sdv.bv.ap": "Biologie végétale/Amélioration des plantes",
    "sdv.bv.bot": "Biologie végétale/Botanique",
    "sdv.bv.pep": "Biologie végétale/Phytopathologie et phytopharmacie",
    "sdv.bio": "Biotechnologies",
    "sdv.can": "Cancer",
    "sdv.ee": "Ecologie, Environnement",
    "sdv.ee.bio": "Ecologie, Environnement/Bioclimatologie",
    "sdv.ee.eco": "Ecologie, Environnement/Ecosystèmes",
    "sdv.ee.ieo": "Ecologie, Environnement/Interactions entre organismes",
    "sdv.ee.sant": "Ecologie, Environnement/Santé",
    "sdv.eth": "Ethique",
    "sdv.gen": "Génétique",
    "sdv.gen.ga": "Génétique/Génétique animale",
    "sdv.gen.gpl": "Génétique/Génétique des plantes",
    "sdv.gen.gpo": "Génétique/Génétique des populations [q-bio.PE]",
    "sdv.gen.gh": "Génétique/Génétique humaine",
    "sdv.imm": "Immunologie",
    "sdv.imm.all": "Immunologie/Allergologie",
    "sdv.imm.ia": "Immunologie/Immunité adaptative",
    "sdv.imm.ii": "Immunologie/Immunité innée",
    "sdv.imm.imm": "Immunologie/Immunothérapie",
    "sdv.imm.vac": "Immunologie/Vaccinologie",
    "sdv.ib": "Ingénierie biomédicale",
    "sdv.ib.bio": "Ingénierie biomédicale/Biomatériaux",
    "sdv.ib.ima": "Ingénierie biomédicale/Imagerie",
    "sdv.ib.mn": "Ingénierie biomédicale/Médecine nucléaire",
    "sdv.ida": "Ingénierie des aliments",
    "sdv.ida.sma": "Ingénierie des aliments/domain_sdv.ida.sma",
    "sdv.mp": "Microbiologie et Parasitologie",
    "sdv.mp.bac": "Microbiologie et Parasitologie/Bactériologie",
    "sdv.mp.myc": "Microbiologie et Parasitologie/Mycologie",
    "sdv.mp.par": "Microbiologie et Parasitologie/Parasitologie",
    "sdv.mp.pro": "Microbiologie et Parasitologie/Protistologie",
    "sdv.mp.vir": "Microbiologie et Parasitologie/Virologie",
    "sdv.mp.prb": "Microbiologie et Parasitologie/domain_sdv.mp.prb",
    "sdv.mp.prb.bif": "Microbiologie et Parasitologie/domain_sdv.mp.prb/domain_sdv.mp.prb.bif",
    "sdv.mp.prb.lac": "Microbiologie et Parasitologie/domain_sdv.mp.prb/domain_sdv.mp.prb.lac",
    "sdv.mhep": "Médecine humaine et pathologie",
    "sdv.mhep.aha": "Médecine humaine et pathologie/Anatomie, Histologie, Anatomopathologie [q-bio.TO]",
    "sdv.mhep.csc": "Médecine humaine et pathologie/Cardiologie et système cardiovasculaire",
    "sdv.mhep.chi": "Médecine humaine et pathologie/Chirurgie",
    "sdv.mhep.derm": "Médecine humaine et pathologie/Dermatologie",
    "sdv.mhep.em": "Médecine humaine et pathologie/Endocrinologie et métabolisme",
    "sdv.mhep.geo": "Médecine humaine et pathologie/Gynécologie et obstétrique",
    "sdv.mhep.geg": "Médecine humaine et pathologie/Gériatrie et gérontologie",
    "sdv.mhep.hem": "Médecine humaine et pathologie/Hématologie",
    "sdv.mhep.heg": "Médecine humaine et pathologie/Hépatologie et Gastroentérologie",
    "sdv.mhep.mi": "Médecine humaine et pathologie/Maladies infectieuses",
    "sdv.mhep.me": "Médecine humaine et pathologie/Maladies émergentes",
    "sdv.mhep.os": "Médecine humaine et pathologie/Organes des sens",
    "sdv.mhep.phy": "Médecine humaine et pathologie/Physiologie [q-bio.TO]",
    "sdv.mhep.psr": "Médecine humaine et pathologie/Pneumologie et système respiratoire",
    "sdv.mhep.psm": "Médecine humaine et pathologie/Psychiatrie et santé mentale",
    "sdv.mhep.ped": "Médecine humaine et pathologie/Pédiatrie",
    "sdv.mhep.rsoa": "Médecine humaine et pathologie/Rhumatologie et système ostéo-articulaire",
    "sdv.mhep.un": "Médecine humaine et pathologie/Urologie et Néphrologie",
    "sdv.neu": "Neurosciences [q-bio.NC]",
    "sdv.neu.nb": "Neurosciences [q-bio.NC]/Neurobiologie",
    "sdv.neu.pc": "Neurosciences [q-bio.NC]/Psychologie et comportements",
    "sdv.neu.sc": "Neurosciences [q-bio.NC]/Sciences cognitives",
    "sdv.spee": "Santé publique et épidémiologie",
    "sdv.sa": "Sciences agricoles",
    "sdv.sa.aep": "Sciences agricoles/Agriculture, économie et politique",
    "sdv.sa.agro": "Sciences agricoles/Agronomie",
    "sdv.sa.hort": "Sciences agricoles/Horticulture",
    "sdv.sa.spa": "Sciences agricoles/Science des productions animales",
    "sdv.sa.sds": "Sciences agricoles/Science des sols",
    "sdv.sa.sta": "Sciences agricoles/Sciences et techniques de l'agriculture",
    "sdv.sa.stp": "Sciences agricoles/Sciences et techniques des pêches",
    "sdv.sa.sf": "Sciences agricoles/Sylviculture, foresterie",
    "sdv.sa.zoo": "Sciences agricoles/Zootechnie",
    "sdv.sp": "Sciences pharmaceutiques",
    "sdv.sp.med": "Sciences pharmaceutiques/Médicaments",
    "sdv.sp.pg": "Sciences pharmaceutiques/Pharmacie galénique",
    "sdv.sp.pharma": "Sciences pharmaceutiques/Pharmacologie",
    "sdv.tox": "Toxicologie",
    "sdv.tox.eco": "Toxicologie/Ecotoxicologie",
    "sdv.tox.tca": "Toxicologie/Toxicologie et chaîne alimentaire",
    "sdv.tox.tvm": "Toxicologie/Toxicologie végétale et mycotoxicologie",
  }},
  "shs": { label: "Sciences de l'Homme et Société", children: {
    "shs.anthro-bio": "Anthropologie biologique",
    "shs.anthro-se": "Anthropologie sociale et ethnologie",
    "shs.archi": "Architecture, aménagement de l'espace",
    "shs.archeo": "Archéologie et Préhistoire",
    "shs.art": "Art et histoire de l'art",
    "shs.droit": "Droit",
    "shs.demo": "Démographie",
    "shs.eco": "Economies et finances",
    "shs.eco.eco": "Economies et finances/domain_shs.eco.eco",
    "shs.eco.fin": "Economies et finances/domain_shs.eco.fin",
    "shs.edu": "Education",
    "shs.class": "Etudes classiques",
    "shs.envir": "Etudes de l'environnement",
    "shs.genre": "Etudes sur le genre",
    "shs.gestion": "Gestion et management",
    "shs.gestion.compta": "Gestion et management/domain_shs.gestion.compta",
    "shs.gestion.droit": "Gestion et management/domain_shs.gestion.droit",
    "shs.gestion.entrep": "Gestion et management/domain_shs.gestion.entrep",
    "shs.gestion.fin": "Gestion et management/domain_shs.gestion.fin",
    "shs.gestion.lang": "Gestion et management/domain_shs.gestion.lang",
    "shs.gestion.langue": "Gestion et management/domain_shs.gestion.langue",
    "shs.gestion.man-op": "Gestion et management/domain_shs.gestion.man-op",
    "shs.gestion.man-re": "Gestion et management/domain_shs.gestion.man-re",
    "shs.gestion.mark": "Gestion et management/domain_shs.gestion.mark",
    "shs.gestion.org": "Gestion et management/domain_shs.gestion.org",
    "shs.gestion.rech-op": "Gestion et management/domain_shs.gestion.rech-op",
    "shs.gestion.strat": "Gestion et management/domain_shs.gestion.strat",
    "shs.gestion.strat-pol": "Gestion et management/domain_shs.gestion.strat-pol",
    "shs.geo": "Géographie",
    "shs.hist": "Histoire",
    "shs.hisphilso": "Histoire, Philosophie et Sociologie des sciences",
    "shs.museo": "Héritage culturel et muséologie",
    "shs.langue": "Linguistique",
    "shs.langue.comp": "Linguistique/domain_shs.langue.comp",
    "shs.langue.diag": "Linguistique/domain_shs.langue.diag",
    "shs.langue.hist": "Linguistique/domain_shs.langue.hist",
    "shs.langue.lexico": "Linguistique/domain_shs.langue.lexico",
    "shs.langue.morp": "Linguistique/domain_shs.langue.morp",
    "shs.langue.pragmatics": "Linguistique/domain_shs.langue.pragmatics",
    "shs.langue.seman": "Linguistique/domain_shs.langue.seman",
    "shs.langue.semantics": "Linguistique/domain_shs.langue.semantics",
    "shs.langue.socio": "Linguistique/domain_shs.langue.socio",
    "shs.langue.text": "Linguistique/domain_shs.langue.text",
    "shs.litt": "Littératures",
    "shs.musiq": "Musique, musicologie et arts de la scène",
    "shs.stat": "Méthodes et statistiques",
    "shs.phil": "Philosophie",
    "shs.phil.action": "Philosophie/domain_shs.phil.action",
    "shs.phil.epistemo": "Philosophie/domain_shs.phil.epistemo",
    "shs.phil.esthetics": "Philosophie/domain_shs.phil.esthetics",
    "shs.phil.ethics": "Philosophie/domain_shs.phil.ethics",
    "shs.phil.language": "Philosophie/domain_shs.phil.language",
    "shs.phil.logic": "Philosophie/domain_shs.phil.logic",
    "shs.phil.metaphysics": "Philosophie/domain_shs.phil.metaphysics",
    "shs.phil.mind": "Philosophie/domain_shs.phil.mind",
    "shs.phil.perception": "Philosophie/domain_shs.phil.perception",
    "shs.psy": "Psychologie",
    "shs.relig": "Religions",
    "shs.scipo": "Science politique",
    "shs.info": "Sciences de l'information et de la communication",
    "shs.info.autr": "Sciences de l'information et de la communication/domain_shs.info.autr",
    "shs.info.bibl": "Sciences de l'information et de la communication/domain_shs.info.bibl",
    "shs.info.cine": "Sciences de l'information et de la communication/domain_shs.info.cine",
    "shs.info.coll": "Sciences de l'information et de la communication/domain_shs.info.coll",
    "shs.info.comm": "Sciences de l'information et de la communication/domain_shs.info.comm",
    "shs.info.conf": "Sciences de l'information et de la communication/domain_shs.info.conf",
    "shs.info.docu": "Sciences de l'information et de la communication/domain_shs.info.docu",
    "shs.info.droi": "Sciences de l'information et de la communication/domain_shs.info.droi",
    "shs.info.econ": "Sciences de l'information et de la communication/domain_shs.info.econ",
    "shs.info.edit": "Sciences de l'information et de la communication/domain_shs.info.edit",
    "shs.info.educ": "Sciences de l'information et de la communication/domain_shs.info.educ",
    "shs.info.espa": "Sciences de l'information et de la communication/domain_shs.info.espa",
    "shs.info.geop": "Sciences de l'information et de la communication/domain_shs.info.geop",
    "shs.info.gest": "Sciences de l'information et de la communication/domain_shs.info.gest",
    "shs.info.hist": "Sciences de l'information et de la communication/domain_shs.info.hist",
    "shs.info.hype": "Sciences de l'information et de la communication/domain_shs.info.hype",
    "shs.info.inge": "Sciences de l'information et de la communication/domain_shs.info.inge",
    "shs.info.medi": "Sciences de l'information et de la communication/domain_shs.info.medi",
    "shs.info.muse": "Sciences de l'information et de la communication/domain_shs.info.muse",
    "shs.info.orga": "Sciences de l'information et de la communication/domain_shs.info.orga",
    "shs.info.soci": "Sciences de l'information et de la communication/domain_shs.info.soci",
    "shs.info.theo": "Sciences de l'information et de la communication/domain_shs.info.theo",
    "shs.socio": "Sociologie",
    "shs.sport": "Sport",
    "shs.sport.ags": "Sport/Analyse du geste sportif",
    "shs.sport.ds": "Sport/Disciplines sportives",
    "shs.sport.eca": "Sport/Entraîner, coacher et accompagner",
    "shs.sport.its": "Sport/Ingénierie et technologie du sport",
    "shs.sport.ps": "Sport/Physiologie du sport",
    "shs.sport.ss": "Sport/Santé du sportif",
    "shs.sport.scs": "Sport/Sciences cognitives du sport",
    "shs.sport.shps": "Sport/Sciences humaines, politiques et sociales du sport",
  }},
  "spi": { label: "Sciences de l'ingénieur [physics]", children: {
    "spi.acou": "Acoustique [physics.class-ph]",
    "spi.auto": "Automatique / Robotique",
    "spi.other": "Autre",
    "spi.elec": "Electromagnétisme",
    "spi.tron": "Electronique",
    "spi.nrj": "Energie électrique",
    "spi.gciv": "Génie civil",
    "spi.gciv.cd": "Génie civil/Construction durable",
    "spi.gciv.ch": "Génie civil/Construction hydraulique",
    "spi.gciv.dv": "Génie civil/Dynamique, vibrations",
    "spi.gciv.ec": "Génie civil/Eco-conception",
    "spi.gciv.gcn": "Génie civil/Génie civil nucléaire",
    "spi.gciv.geotech": "Génie civil/Géotechnique",
    "spi.gciv.it": "Génie civil/Infrastructures de transport",
    "spi.gciv.mat": "Génie civil/Matériaux composites et construction",
    "spi.gciv.risq": "Génie civil/Risques",
    "spi.gciv.rhea": "Génie civil/Réhabilitation",
    "spi.gciv.struct": "Génie civil/Structures",
    "spi.gproc": "Génie des procédés",
    "spi.mat": "Matériaux",
    "spi.nano": "Micro et nanotechnologies/Microélectronique",
    "spi.fluid": "Milieux fluides et réactifs",
    "spi.meca": "Mécanique [physics.med-ph]",
    "spi.meca.biom": "Mécanique [physics.med-ph]/Biomécanique [physics.med-ph]",
    "spi.meca.geme": "Mécanique [physics.med-ph]/Génie mécanique [physics.class-ph]",
    "spi.meca.msmeca": "Mécanique [physics.med-ph]/Matériaux et structures en mécanique [physics.class-ph]",
    "spi.meca.mefl": "Mécanique [physics.med-ph]/Mécanique des fluides [physics.class-ph]",
    "spi.meca.mema": "Mécanique [physics.med-ph]/Mécanique des matériaux [physics.class-ph]",
    "spi.meca.solid": "Mécanique [physics.med-ph]/Mécanique des solides [physics.class-ph]",
    "spi.meca.stru": "Mécanique [physics.med-ph]/Mécanique des structures [physics.class-ph]",
    "spi.meca.ther": "Mécanique [physics.med-ph]/Thermique [physics.class-ph]",
    "spi.meca.vibr": "Mécanique [physics.med-ph]/Vibrations [physics.class-ph]",
    "spi.opti": "Optique / photonique",
    "spi.plasma": "Plasmas",
    "spi.signal": "Traitement du signal et de l'image [eess.SP]",
  }},
  "stat": { label: "Statistiques [stat]", children: {
    "stat.ap": "Applications [stat.AP]",
    "stat.ot": "Autres [stat.ML]",
    "stat.co": "Calcul [stat.CO]",
    "stat.ml": "Machine Learning [stat.ML]",
    "stat.me": "Méthodologie [stat.ME]",
    "stat.th": "Théorie [stat.TH]",
  }},
};
