const DOMAIN_TREE = {
  "chim": { label: "Chimie", children: {
    "chim.othe": { label: "Autre", children: {} },
    "chim.cata": { label: "Catalyse", children: {} },
    "chim.chem": { label: "Chemo-informatique", children: {} },
    "chim.anal": { label: "Chimie analytique", children: {} },
    "chim.coor": { label: "Chimie de coordination", children: {} },
    "chim.inor": { label: "Chimie inorganique", children: {} },
    "chim.orga": { label: "Chimie organique", children: {} },
    "chim.ther": { label: "Chimie thérapeutique", children: {} },
    "chim.cris": { label: "Cristallographie", children: {} },
    "chim.geni": { label: "Génie chimique", children: {} },
    "chim.mate": { label: "Matériaux", children: {} },
    "chim.poly": { label: "Polymères", children: {} },
    "chim.radio": { label: "Radiochimie", children: {} },
    "chim.theo": { label: "ou physique", children: {} },
  }},
  "info": { label: "Informatique [cs]", children: {
    "info.info-ds": { label: "Algorithme et structure de données [cs.DS]", children: {} },
    "info.info-na": { label: "Analyse numérique [cs.NA]", children: {} },
    "info.info-lg": { label: "Apprentissage [cs.LG]", children: {} },
    "info.info-ar": { label: "Architectures Matérielles [cs.AR]", children: {} },
    "info.info-ao": { label: "Arithmétique des ordinateurs", children: {} },
    "info.info-au": { label: "Automatique", children: {} },
    "info.info-oh": { label: "Autre [cs.OH]", children: {} },
    "info.info-db": { label: "Base de données [cs.DB]", children: {} },
    "info.info-dl": { label: "Bibliothèque électronique [cs.DL]", children: {} },
    "info.info-bi": { label: "Bio-informatique [q-bio.QM]", children: {} },
    "info.info-bt": { label: "Biotechnologie", children: {} },
    "info.info-sc": { label: "Calcul formel [cs.SC]", children: {} },
    "info.info-dc": { label: "Calcul parallèle, distribué et partagé [cs.DC]", children: {} },
    "info.info-cc": { label: "Complexité [cs.CC]", children: {} },
    "info.info-cr": { label: "Cryptographie et sécurité [cs.CR]", children: {} },
    "info.eiah": { label: "Environnements Informatiques pour l'Apprentissage Humain", children: {} },
    "info.info-se": { label: "Génie logiciel [cs.SE]", children: {} },
    "info.info-cg": { label: "Géométrie algorithmique [cs.CG]", children: {} },
    "info.info-im": { label: "Imagerie médicale", children: {} },
    "info.comp": { label: "Informatique [cs]", children: {} },
    "info.par": { label: "Informatique [cs]", children: {} },
    "info.info-cl": { label: "Informatique et langage [cs.CL]", children: {} },
    "info.info-gt": { label: "Informatique et théorie des jeux [cs.GT]", children: {} },
    "info.info-mc": { label: "Informatique mobile", children: {} },
    "info.info-iu": { label: "Informatique ubiquitaire", children: {} },
    "info.info-ia": { label: "Ingénierie assistée par ordinateur", children: {} },
    "info.info-ce": { label: "Ingénierie, finance et science [cs.CE]", children: {} },
    "info.info-ai": { label: "Intelligence artificielle [cs.AI]", children: {} },
    "info.info-hc": { label: "Interface homme-machine [cs.HC]", children: {} },
    "info.info-pl": { label: "Langage de programmation [cs.PL]", children: {} },
    "info.info-gl": { label: "Littérature générale [cs.GL]", children: {} },
    "info.info-ms": { label: "Logiciel mathématique [cs.MS]", children: {} },
    "info.info-lo": { label: "Logique en informatique [cs.LO]", children: {} },
    "info.info-dm": { label: "Mathématique discrète [cs.DM]", children: {} },
    "info.info-mo": { label: "Modélisation et simulation", children: {} },
    "info.info-mm": { label: "Multimédia [cs.MM]", children: {} },
    "info.info-cy": { label: "Ordinateur et société [cs.CY]", children: {} },
    "info.info-pf": { label: "Performance et fiabilité [cs.PF]", children: {} },
    "info.info-ir": { label: "Recherche d'information [cs.IR]", children: {} },
    "info.info-ro": { label: "Recherche opérationnelle [math.OC]", children: {} },
    "info.info-rb": { label: "Robotique [cs.RO]", children: {} },
    "info.info-ne": { label: "Réseau de neurones [cs.NE]", children: {} },
    "info.info-ni": { label: "Réseaux et télécommunications [cs.NI]", children: {} },
    "info.info-si": { label: "Réseaux sociaux et d'information [cs.SI]", children: {} },
    "info.info-sd": { label: "Son [cs.SD]", children: {} },
    "info.info-gr": { label: "Synthèse d'image et réalité virtuelle [cs.GR]", children: {} },
    "info.info-os": { label: "Système d'exploitation [cs.OS]", children: {} },
    "info.info-ma": { label: "Système multi-agents [cs.MA]", children: {} },
    "info.info-es": { label: "Systèmes embarqués", children: {} },
    "info.info-sy": { label: "Systèmes et contrôle [cs.SY]", children: {} },
    "info.info-et": { label: "Technologies Émergeantes [cs.ET]", children: {} },
    "info.info-it": { label: "Théorie de l'information [cs.IT]", children: {} },
    "info.info-fl": { label: "Théorie et langage formel [cs.FL]", children: {} },
    "info.info-ti": { label: "Traitement des images [eess.IV]", children: {} },
    "info.info-ts": { label: "Traitement du signal et de l'image [eess.SP]", children: {} },
    "info.info-tt": { label: "Traitement du texte et du document", children: {} },
    "info.info-cv": { label: "Vision par ordinateur et reconnaissance de formes [cs.CV]", children: {} },
    "info.info-wb": { label: "Web", children: {} },
  }},
  "math": { label: "Mathématiques [math]", children: {
    "math.math-ac": { label: "Algèbre commutative [math.AC]", children: {} },
    "math.math-oa": { label: "Algèbres d'opérateurs [math.OA]", children: {} },
    "math.math-qa": { label: "Algèbres quantiques [math.QA]", children: {} },
    "math.math-ca": { label: "Analyse classique [math.CA]", children: {} },
    "math.math-fa": { label: "Analyse fonctionnelle [math.FA]", children: {} },
    "math.math-na": { label: "Analyse numérique [math.NA]", children: {} },
    "math.math-ra": { label: "Anneaux et algèbres [math.RA]", children: {} },
    "math.math-ct": { label: "Catégories et ensembles [math.CT]", children: {} },
    "math.math-co": { label: "Combinatoire [math.CO]", children: {} },
    "math.math-ap": { label: "Equations aux dérivées partielles [math.AP]", children: {} },
    "math.math-ag": { label: "Géométrie algébrique [math.AG]", children: {} },
    "math.math-dg": { label: "Géométrie différentielle [math.DG]", children: {} },
    "math.math-mg": { label: "Géométrie métrique [math.MG]", children: {} },
    "math.math-sg": { label: "Géométrie symplectique [math.SG]", children: {} },
    "math.math-ho": { label: "Histoire et perspectives sur les mathématiques [math.HO]", children: {} },
    "math.math-kt": { label: "K-théorie et homologie [math.KT]", children: {} },
    "math.math-lo": { label: "Logique [math.LO]", children: {} },
    "math.appl": { label: "Mathématiques [math]", children: {} },
    "math.tr-img": { label: "Mathématiques [math]", children: {} },
    "math.math-gm": { label: "Mathématiques générales [math.GM]", children: {} },
    "math.math-oc": { label: "Optimisation et contrôle [math.OC]", children: {} },
    "math.math-mp": { label: "Physique mathématique [math-ph]", children: {} },
    "math.math-pr": { label: "Probabilités [math.PR]", children: {} },
    "math.math-st": { label: "Statistiques [math.ST]", children: {} },
    "math.math-ds": { label: "Systèmes dynamiques [math.DS]", children: {} },
    "math.math-it": { label: "Théorie de l'information et codage [math.IT]", children: {} },
    "math.math-gr": { label: "Théorie des groupes [math.GR]", children: {} },
    "math.math-nt": { label: "Théorie des nombres [math.NT]", children: {} },
    "math.math-rt": { label: "Théorie des représentations [math.RT]", children: {} },
    "math.math-sp": { label: "Théorie spectrale [math.SP]", children: {} },
    "math.math-at": { label: "Topologie algébrique [math.AT]", children: {} },
    "math.math-gn": { label: "Topologie générale [math.GN]", children: {} },
    "math.math-gt": { label: "Topologie géométrique [math.GT]", children: {} },
    "math.math-cv": { label: "Variables complexes [math.CV]", children: {} },
  }},
  "phys": { label: "Physique [physics]", children: {
    "phys.hist": { label: "Articles anciens", children: {} },
    "phys.astr": { label: "Astrophysique [astro-ph]", children: {
      "phys.astr.ga": "Astrophysique galactique [astro-ph.GA]",
      "phys.astr.sr": "Astrophysique stellaire et solaire [astro-ph.SR]",
      "phys.astr.co": "Cosmologie et astrophysique extra-galactique [astro-ph.CO]",
      "phys.astr.im": "Instrumentation et méthodes pour l'astrophysique [astro-ph.IM]",
      "phys.astr.he": "Phénomènes cosmiques de haute energie [astro-ph.HE]",
      "phys.astr.ep": "Planétologie et astrophysique de la terre [astro-ph.EP]",
    } },
    "phys.cond": { label: "Matière Condensée [cond-mat]", children: {
      "phys.cond.cm-gen": "Autre [cond-mat.other]",
      "phys.cond.cm-sce": "Electrons fortement corrélés [cond-mat.str-el]",
      "phys.cond.gas": "Gaz Quantiques [cond-mat.quant-gas]",
      "phys.cond.cm-scm": "Matière Molle [cond-mat.soft]",
      "phys.cond.cm-sm": "Mécanique statistique [cond-mat.stat-mech]",
      "phys.cond.cm-ms": "Science des matériaux [cond-mat.mtrl-sci]",
      "phys.cond.cm-s": "Supraconductivité [cond-mat.supr-con]",
      "phys.cond.cm-ds-nn": "Systèmes désordonnés et réseaux de neurones [cond-mat.dis-nn]",
      "phys.cond.cm-msqhe": "Systèmes mésoscopiques et effet Hall quantique [cond-mat.mes-hall]",
    } },
    "phys.meca": { label: "Mécanique [physics]", children: {
      "phys.meca.acou": "Acoustique [physics.class-ph]",
      "phys.meca.biom": "Biomécanique [physics.med-ph]",
      "phys.meca.geme": "Génie mécanique [physics.class-ph]",
      "phys.meca.msmeca": "Matériaux et structures en mécanique [physics.class-ph]",
      "phys.meca.mefl": "Mécanique des fluides [physics.class-ph]",
      "phys.meca.mema": "Mécanique des matériaux [physics.class-ph]",
      "phys.meca.solid": "Mécanique des solides [physics.class-ph]",
      "phys.meca.stru": "Mécanique des structures [physics.class-ph]",
      "phys.meca.ther": "Thermique [physics.class-ph]",
      "phys.meca.vibr": "Vibrations [physics.class-ph]",
    } },
    "phys.nexp": { label: "Physique Nucléaire Expérimentale [nucl-ex]", children: {} },
    "phys.nucl": { label: "Physique Nucléaire Théorique [nucl-th]", children: {} },
    "phys.qphy": { label: "Physique Quantique [quant-ph]", children: {} },
    "phys.phys": { label: "Physique [physics]", children: {
      "phys.phys.phys-atm-ph": "Agrégats Moléculaires et Atomiques [physics.atm-clus]",
      "phys.phys.phys-data-an": "Analyse de données, Statistiques et Probabilités [physics.data-an]",
      "phys.phys.phys-bio-ph": "Biophysique [physics.bio-ph]",
      "phys.phys.phys-chem-ph": "Chimie-Physique [physics.chem-ph]",
      "phys.phys.phys-flu-dyn": "Dynamique des Fluides [physics.flu-dyn]",
      "phys.phys.phys-ed-ph": "Enseignement de la physique [physics.ed-ph]",
      "phys.phys.phys-geo-ph": "Géophysique [physics.geo-ph]",
      "phys.phys.phys-hist-ph": "Histoire de la Physique [physics.hist-ph]",
      "phys.phys.phys-ins-det": "Instrumentations et Détecteurs [physics.ins-det]",
      "phys.phys.phys-optics": "Optique [physics.optics]",
      "phys.phys.phys-pop-ph": "Physique : vulgarisation [physics.pop-ph]",
      "phys.phys.phys-ao-ph": "Physique Atmosphérique et Océanique [physics.ao-ph]",
      "phys.phys.phys-atom-ph": "Physique Atomique [physics.atom-ph]",
      "phys.phys.phys-class-ph": "Physique Classique [physics.class-ph]",
      "phys.phys.phys-gen-ph": "Physique Générale [physics.gen-ph]",
      "phys.phys.phys-med-ph": "Physique Médicale [physics.med-ph]",
      "phys.phys.phys-comp-ph": "Physique Numérique [physics.comp-ph]",
      "phys.phys.phys-space-ph": "Physique de l'espace [physics.space-ph]",
      "phys.phys.phys-acc-ph": "Physique des accélérateurs [physics.acc-ph]",
      "phys.phys.phys-plasm-ph": "Physique des plasmas [physics.plasm-ph]",
      "phys.phys.phys-soc-ph": "Physique et Société [physics.soc-ph]",
    } },
    "phys.hexp": { label: "Physique des Hautes Energies - Expérience [hep-ex]", children: {} },
    "phys.hphe": { label: "Physique des Hautes Energies - Phénoménologie [hep-ph]", children: {} },
    "phys.hlat": { label: "Physique des Hautes Energies - Réseau [hep-lat]", children: {} },
    "phys.hthe": { label: "Physique des Hautes Energies - Théorie [hep-th]", children: {} },
    "phys.mphy": { label: "Physique mathématique [math-ph]", children: {} },
    "phys.grqc": { label: "Relativité Générale et Cosmologie Quantique [gr-qc]", children: {} },
  }},
  "sdu": { label: "Planète et Univers [physics]", children: {
    "sdu.astr": { label: "Astrophysique [astro-ph]", children: {
      "sdu.astr.ga": "Astrophysique galactique [astro-ph.GA]",
      "sdu.astr.sr": "Astrophysique stellaire et solaire [astro-ph.SR]",
      "sdu.astr.co": "Cosmologie et astrophysique extra-galactique [astro-ph.CO]",
      "sdu.astr.im": "Instrumentation et méthodes pour l'astrophysique [astro-ph.IM]",
      "sdu.astr.he": "Phénomènes cosmiques de haute energie [astro-ph.HE]",
      "sdu.astr.ep": "Planétologie et astrophysique de la terre [astro-ph.EP]",
    } },
    "sdu.other": { label: "Autre", children: {} },
    "sdu.envi": { label: "Interfaces continentales, environnement", children: {} },
    "sdu.ocean": { label: "Océan, Atmosphère", children: {} },
    "sdu.astro": { label: "Planète et Univers [physics]", children: {} },
    "sdu.stu": { label: "Sciences de la Terre", children: {
      "sdu.stu.cl": "Climatologie",
      "sdu.stu.gl": "Glaciologie",
      "sdu.stu.gc": "Géochimie",
      "sdu.stu.ag": "Géologie appliquée",
      "sdu.stu.gm": "Géomorphologie",
      "sdu.stu.gp": "Géophysique [physics.geo-ph]",
      "sdu.stu.hy": "Hydrologie",
      "sdu.stu.mi": "Minéralogie",
      "sdu.stu.me": "Météorologie",
      "sdu.stu.oc": "Océanographie",
      "sdu.stu.pg": "Paléontologie",
      "sdu.stu.pl": "Planétologie",
      "sdu.stu.pe": "Pétrographie",
      "sdu.stu.st": "Stratigraphie",
      "sdu.stu.te": "Tectonique",
      "sdu.stu.vo": "Volcanologie",
    } },
  }},
  "nlin": { label: "Science non linéaire [physics]", children: {
    "nlin.nlin-ao": { label: "Adaptation et Systèmes auto-organisés [nlin.AO]", children: {} },
    "nlin.nlin-cg": { label: "Automates cellulaires et gaz sur réseau [nlin.CG]", children: {} },
    "nlin.nlin-cd": { label: "Dynamique Chaotique [nlin.CD]", children: {} },
    "nlin.nlin-ps": { label: "Formation de Structures et Solitons [nlin.PS]", children: {} },
    "nlin.nlin-si": { label: "Systèmes Solubles et Intégrables [nlin.SI]", children: {} },
  }},
  "scco": { label: "Sciences cognitives", children: {
    "scco.comp": { label: "Informatique", children: {} },
    "scco.ling": { label: "Linguistique", children: {} },
    "scco.neur": { label: "Neurosciences", children: {} },
    "scco.psyc": { label: "Psychologie", children: {} },
    "scco.cogpsy": { label: "Psychologie cognitive", children: {} },
    "scco.evolpsy": { label: "Psychologie évolutionniste", children: {} },
    "scco.reasonning": { label: "Sciences cognitives", children: {} },
    "scco.socialpsy": { label: "Psychologie sociale", children: {} },
    "scco.neurosc": { label: "Neurosciences", children: {} },
    "scco.cogdynamics": { label: "Sciences cognitives", children: {} },
    "scco.devpsy": { label: "Sciences cognitives", children: {} },
    "scco.psyemo": { label: "Sciences cognitives", children: {} },
    "scco.naivepsyandsimu": { label: "Sciences cognitives", children: {} },
  }},
  "shs": { label: "Sciences de l'Homme et Société", children: {
    "shs.anthro-bio": { label: "Anthropologie biologique", children: {} },
    "shs.anthro-se": { label: "Anthropologie sociale et ethnologie", children: {} },
    "shs.archi": { label: "Architecture, aménagement de l'espace", children: {} },
    "shs.archeo": { label: "Archéologie et Préhistoire", children: {} },
    "shs.art": { label: "Art et histoire de l'art", children: {} },
    "shs.droit": { label: "Droit", children: {} },
    "shs.demo": { label: "Démographie", children: {} },
    "shs.eco": { label: "Economies et finances", children: {} },
    "shs.edu": { label: "Education", children: {} },
    "shs.class": { label: "Etudes classiques", children: {} },
    "shs.envir": { label: "Etudes de l'environnement", children: {} },
    "shs.genre": { label: "Etudes sur le genre", children: {} },
    "shs.gestion": { label: "Gestion et management", children: {} },
    "shs.geo": { label: "Géographie", children: {} },
    "shs.hist": { label: "Histoire", children: {} },
    "shs.hisphilso": { label: "Histoire, Philosophie et Sociologie des sciences", children: {} },
    "shs.museo": { label: "Héritage culturel et muséologie", children: {} },
    "shs.langue": { label: "Linguistique", children: {} },
    "shs.litt": { label: "Littératures", children: {} },
    "shs.musiq": { label: "Musique, musicologie et arts de la scène", children: {} },
    "shs.stat": { label: "Méthodes et statistiques", children: {} },
    "shs.phil": { label: "Philosophie", children: {
      "shs.phil.mind": "Philosophie de l'esprit",
      "shs.phil.language": "Philosophie du langage",
      "shs.phil.epistemo": "Épistémologie",
      "shs.phil.action": "Philosophie de l'action",
      "shs.phil.perception": "Perception",
      "shs.phil.metaphysics": "Métaphysique",
      "shs.phil.logic": "Logique",
      "shs.phil.ethics": "Éthique",
      "shs.phil.esthetics": "Esthétique",
    } },
    "shs.psy": { label: "Psychologie", children: {} },
    "shs.relig": { label: "Religions", children: {} },
    "shs.scipo": { label: "Science politique", children: {} },
    "shs.gest-risq": { label: "Gestion des risques", children: {} },
    "shs.info": { label: "Sciences de l'information et de la communication", children: {} },
    "shs.socio": { label: "Sociologie", children: {} },
    "shs.sport": { label: "Sport", children: {
      "shs.sport.ags": "Analyse du geste sportif",
      "shs.sport.ds": "Disciplines sportives",
      "shs.sport.eca": "Entraîner, coacher et accompagner",
      "shs.sport.its": "Ingénierie et technologie du sport",
      "shs.sport.ps": "Physiologie du sport",
      "shs.sport.ss": "Santé du sportif",
      "shs.sport.scs": "Sciences cognitives du sport",
      "shs.sport.shps": "Sciences humaines, politiques et sociales du sport",
    } },
  }},
  "sde": { label: "Sciences de l'environnement", children: {
    "sde.be": { label: "Biodiversité et Ecologie", children: {} },
    "sde.es": { label: "Environnement et Société", children: {} },
    "sde.ie": { label: "Ingénierie de l'environnement", children: {} },
    "sde.mcg": { label: "Milieux et Changements globaux", children: {} },
    "sde.plt": { label: "Sciences de l'environnement", children: {} },
    "sde.plan": { label: "Sciences de l'environnement", children: {} },
    "sde.dev-dur": { label: "Sciences de l'environnement", children: {} },
    "sde.sds": { label: "Sciences de l'environnement", children: {} },
    "sde.er": { label: "Sciences de l'environnement", children: {} },
  }},
  "spi": { label: "Sciences de l'ingénieur [physics]", children: {
    "spi.acou": { label: "Acoustique [physics.class-ph]", children: {} },
    "spi.other": { label: "Autre", children: {} },
    "spi.elec": { label: "Electromagnétisme", children: {} },
    "spi.tron": { label: "Electronique", children: {} },
    "spi.nrj": { label: "Energie électrique", children: {} },
    "spi.gciv": { label: "Génie civil", children: {
      "spi.gciv.cd": "Construction durable",
      "spi.gciv.ch": "Construction hydraulique",
      "spi.gciv.dv": "Dynamique, vibrations",
      "spi.gciv.ec": "Eco-conception",
      "spi.gciv.gcn": "Génie civil nucléaire",
      "spi.gciv.geotech": "Géotechnique",
      "spi.gciv.it": "Infrastructures de transport",
      "spi.gciv.mat": "Matériaux composites et construction",
      "spi.gciv.risq": "Risques",
      "spi.gciv.rhea": "Réhabilitation",
      "spi.gciv.struct": "Structures",
    } },
    "spi.gproc": { label: "Génie des procédés", children: {} },
    "spi.mat": { label: "Matériaux", children: {} },
    "spi.nano": { label: "Microélectronique", children: {} },
    "spi.fluid": { label: "Milieux fluides et réactifs", children: {} },
    "spi.meca": { label: "Mécanique [physics.med-ph]", children: {
      "spi.meca.biom": "Biomécanique [physics.med-ph]",
      "spi.meca.geme": "Génie mécanique [physics.class-ph]",
      "spi.meca.msmeca": "Matériaux et structures en mécanique [physics.class-ph]",
      "spi.meca.mefl": "Mécanique des fluides [physics.class-ph]",
      "spi.meca.mema": "Mécanique des matériaux [physics.class-ph]",
      "spi.meca.solid": "Mécanique des solides [physics.class-ph]",
      "spi.meca.stru": "Mécanique des structures [physics.class-ph]",
      "spi.meca.ther": "Thermique [physics.class-ph]",
      "spi.meca.vibr": "Vibrations [physics.class-ph]",
    } },
    "spi.plasma": { label: "Plasmas", children: {} },
    "spi.auto": { label: "Robotique", children: {} },
    "spi.energ": { label: "Sciences de l'ingénieur [physics]", children: {} },
    "spi.signal": { label: "Traitement du signal et de l'image [eess.SP]", children: {} },
    "spi.opti": { label: "photonique", children: {} },
  }},
  "sdv": { label: "Sciences du Vivant [q-bio]", children: {
    "sdv.aen": { label: "Alimentation et Nutrition", children: {
      "sdv.aen.nut": "Alimentation et Nutrition",
    } },
    "sdv.ot": { label: "Autre [q-bio.OT]", children: {} },
    "sdv.bibs": { label: "Bio-Informatique, Biologie Systémique [q-bio.QM]", children: {} },
    "sdv.bbm": { label: "Biochimie, Biologie Moléculaire", children: {
      "sdv.bbm.bc": "Biochimie [q-bio.BM]",
      "sdv.bbm.bm": "Biologie moléculaire",
      "sdv.bbm.bs": "Biologie structurale [q-bio.BM]",
      "sdv.bbm.bp": "Biophysique",
      "sdv.bbm.gtp": "Génomique, Transcriptomique et Protéomique [q-bio.GN]",
      "sdv.bbm.mn": "Réseaux moléculaires [q-bio.MN]",
    } },
    "sdv.bid": { label: "Biodiversité", children: {
      "sdv.bid.evo": "Evolution [q-bio.PE]",
      "sdv.bid.spt": "Systématique, phylogénie et taxonomie",
    } },
    "sdv.ba": { label: "Biologie animale", children: {
      "sdv.ba.mvsa": "Médecine vétérinaire et santé animale",
      "sdv.ba.zi": "Zoologie des invertébrés",
      "sdv.ba.zv": "Zoologie des vertébrés",
    } },
    "sdv.bc": { label: "Biologie cellulaire", children: {
      "sdv.bc.ic": "Interactions cellulaires [q-bio.CB]",
      "sdv.bc.bc": "Organisation et fonctions cellulaires [q-bio.SC]",
    } },
    "sdv.bdlr": { label: "Biologie de la reproduction", children: {
      "sdv.bdlr.ra": "Reproduction asexuée",
      "sdv.bdlr.rs": "Reproduction sexuée",
    } },
    "sdv.bdd": { label: "Biologie du développement", children: {
      "sdv.bdd.eo": "Embryologie et organogenèse",
      "sdv.bdd.gam": "Gamétogenèse",
      "sdv.bdd.mor": "Morphogenèse",
    } },
    "sdv.bv": { label: "Biologie végétale", children: {
      "sdv.bv.ap": "Amélioration des plantes",
      "sdv.bv.bot": "Botanique",
      "sdv.bv.pep": "Phytopathologie et phytopharmacie",
    } },
    "sdv.bio": { label: "Biotechnologies", children: {} },
    "sdv.can": { label: "Cancer", children: {} },
    "sdv.ee": { label: "Ecologie, Environnement", children: {
      "sdv.ee.bio": "Bioclimatologie",
      "sdv.ee.eco": "Ecosystèmes",
      "sdv.ee.ieo": "Interactions entre organismes",
      "sdv.ee.sant": "Santé",
    } },
    "sdv.eth": { label: "Ethique", children: {} },
    "sdv.gen": { label: "Génétique", children: {
      "sdv.gen.ga": "Génétique animale",
      "sdv.gen.gpl": "Génétique des plantes",
      "sdv.gen.gpo": "Génétique des populations [q-bio.PE]",
      "sdv.gen.gh": "Génétique humaine",
    } },
    "sdv.imm": { label: "Immunologie", children: {
      "sdv.imm.all": "Allergologie",
      "sdv.imm.ia": "Immunité adaptative",
      "sdv.imm.ii": "Immunité innée",
      "sdv.imm.imm": "Immunothérapie",
      "sdv.imm.vac": "Vaccinologie",
    } },
    "sdv.ib": { label: "Ingénierie biomédicale", children: {
      "sdv.ib.bio": "Biomatériaux",
      "sdv.ib.ima": "Imagerie",
      "sdv.ib.mn": "Médecine nucléaire",
    } },
    "sdv.ida": { label: "Ingénierie des aliments", children: {
      "sdv.ida.sma": "Ingénierie des aliments",
    } },
    "sdv.mp": { label: "Microbiologie et Parasitologie", children: {
      "sdv.mp.bac": "Bactériologie",
      "sdv.mp.prb": "Microbiologie et Parasitologie",
      "sdv.mp.myc": "Mycologie",
      "sdv.mp.par": "Parasitologie",
      "sdv.mp.pro": "Protistologie",
      "sdv.mp.vir": "Virologie",
    } },
    "sdv.mhep": { label: "Médecine humaine et pathologie", children: {
      "sdv.mhep.aha": "Anatomie, Histologie, Anatomopathologie [q-bio.TO]",
      "sdv.mhep.csc": "Cardiologie et système cardiovasculaire",
      "sdv.mhep.chi": "Chirurgie",
      "sdv.mhep.derm": "Dermatologie",
      "sdv.mhep.em": "Endocrinologie et métabolisme",
      "sdv.mhep.geo": "Gynécologie et obstétrique",
      "sdv.mhep.geg": "Gériatrie et gérontologie",
      "sdv.mhep.hem": "Hématologie",
      "sdv.mhep.heg": "Hépatologie et Gastroentérologie",
      "sdv.mhep.mi": "Maladies infectieuses",
      "sdv.mhep.me": "Maladies émergentes",
      "sdv.mhep.os": "Organes des sens",
      "sdv.mhep.phy": "Physiologie [q-bio.TO]",
      "sdv.mhep.psr": "Pneumologie et système respiratoire",
      "sdv.mhep.psm": "Psychiatrie et santé mentale",
      "sdv.mhep.ped": "Pédiatrie",
      "sdv.mhep.rsoa": "Rhumatologie et système ostéo-articulaire",
      "sdv.mhep.un": "Urologie et Néphrologie",
    } },
    "sdv.neu": { label: "Neurosciences [q-bio.NC]", children: {
      "sdv.neu.nb": "Neurobiologie",
      "sdv.neu.pc": "Psychologie et comportements",
      "sdv.neu.sc": "Sciences cognitives",
    } },
    "sdv.spee": { label: "Santé publique et épidémiologie", children: {} },
    "sdv.sa": { label: "Sciences agricoles", children: {
      "sdv.sa.aep": "Agriculture, économie et politique",
      "sdv.sa.agro": "Agronomie",
      "sdv.sa.hort": "Horticulture",
      "sdv.sa.spa": "Science des productions animales",
      "sdv.sa.sds": "Science des sols",
      "sdv.sa.sta": "Sciences et techniques de l'agriculture",
      "sdv.sa.stp": "Sciences et techniques des pêches",
      "sdv.sa.sf": "Sylviculture, foresterie",
      "sdv.sa.zoo": "Zootechnie",
    } },
    "sdv.sp": { label: "Sciences pharmaceutiques", children: {
      "sdv.sp.med": "Médicaments",
      "sdv.sp.pg": "Pharmacie galénique",
      "sdv.sp.pharma": "Pharmacologie",
    } },
    "sdv.tox": { label: "Toxicologie", children: {
      "sdv.tox.eco": "Ecotoxicologie",
      "sdv.tox.tca": "Toxicologie et chaîne alimentaire",
      "sdv.tox.tvm": "Toxicologie végétale et mycotoxicologie",
    } },
  }},
  "stat": { label: "Statistiques [stat]", children: {
    "stat.ap": { label: "Applications [stat.AP]", children: {} },
    "stat.ot": { label: "Autres [stat.ML]", children: {} },
    "stat.co": { label: "Calcul [stat.CO]", children: {} },
    "stat.ml": { label: "Machine Learning [stat.ML]", children: {} },
    "stat.me": { label: "Méthodologie [stat.ME]", children: {} },
    "stat.th": { label: "Théorie [stat.TH]", children: {} },
  }},
  "qfin": { label: "Économie et finance quantitative [q-fin]", children: {
    "qfin.st": { label: "Econométrie de la finance [q-fin.ST]", children: {} },
    "qfin.gn": { label: "Finance [q-fin.GN]", children: {} },
    "qfin.cp": { label: "Finance quantitative [q-fin.CP]", children: {} },
    "qfin.pm": { label: "Gestion de portefeuilles [q-fin.PM]", children: {} },
    "qfin.rm": { label: "Gestion des risques [q-fin.RM]", children: {} },
    "qfin.tr": { label: "Microstructure des marchés [q-fin.TR]", children: {} },
    "qfin.pr": { label: "Pricing [q-fin.PR]", children: {} },
  }},
}
