const OPERATORS_BY_TYPE = {
  _t: [
    { id: "contains",    label: "contient",       arity: 1 },
    { id: "is",          label: "est exactement", arity: 1 },
    { id: "is_not",      label: "n'est pas",      arity: 1 },
    { id: "starts_with", label: "commence par",   arity: 1 },
  ],
  _s: [
  { id: "is",     label: "est",       arity: 1 },
  { id: "is_not", label: "n'est pas", arity: 1 },
  { id: "exists",     label: "est renseigné",     arity: 0 },
  { id: "not_exists", label: "n'est pas renseigné", arity: 0 },
],
  _domain: [
  { id: "domain_is",     label: "est",     arity: 0 },
  { id: "domain_is_not", label: "n'est pas", arity: 0 },
],
  _i: [
    { id: "eq",      label: "=",      arity: 1 },
    { id: "neq",     label: "≠",      arity: 1 },
  ],
  _id: [
    { id: "is",     label: "est",       arity: 1 },
    { id: "is_not", label: "n'est pas", arity: 1 },
    { id: "exists",     label: "est renseigné",     arity: 0 },
{ id: "not_exists", label: "n'est pas renseigné", arity: 0 },
  ],
  _tdate: [
    { id: "eq",           label: "le",       arity: 1 },
    { id: "before",       label: "avant le", arity: 1 },
    { id: "after",        label: "après le", arity: 1 },
    { id: "date_between", label: "entre",    arity: 2 },
  ],
  _bool: [
    { id: "true",           label: "oui",       arity: 0 },
    { id: "false",       label: "non", arity: 0 },
  ],
};

const FIELDS = [
  { name: "authFullName_t",        label: "Auteur (nom complet)",               type: "_t"     },
  { name: "authFirstName_t",        label: "Prénom",               type: "_t"     },
  { name: "authLastName_t",        label: "Nom de famille",               type: "_t"     },
  { name: "collection_t",            label: "Collection (nom)",           type: "_t"     },
  { name: "collCode_s",            label: "Collection (code)",           type: "_s"     },
  { name: "structure_t",            label: "Structure (nom)",           type: "_t"     },
  { name: "structId_i",            label: "Structure (Id)",           type: "_i"     },
  { name: "doiId_id",              label: "DOI",                  type: "_id"    },
  { name: "authIdHal_s",              label: "IdHal de l'auteur",                  type: "_s"    },
  { name: "publicationDate_tdate", label: "Date de publication",  type: "_tdate" },
  { name: "docType_s",            label: "Type de document",    type: "_s", options: [ 
    { value: "ART", label: "Article de revue" },
    { value: "COMM", label: "Communication dans un congrès" },
    { value: "COUV", label: "Chapitre d'ouvrage" },
    { value: "THESE", label: "Thèse" },
    { value: "MEM", label: "Mémoire" },
    { value: "UNDEFINED", label: "Working Paper" },
    { value: "COUV", label: "Chapitre d'ouvrage" },
    { value: "IMG", label: "Image" },
    { value: "POSTER", label: "Poster" },
    { value: "REPORT", label: "Rapport" },
    { value: "OTHER", label: "Autre type" },
    { value: "OUV", label: "Ouvrage" },
    { value: "BLOG", label: "Billet de blog" },
    { value: "HDR", label: "HDR" },
    { value: "LECTURE", label: "Cours" },
    { value: "VIDEO", label: "Vidéo" },
    { value: "PROCEEDINGS", label: "Proceedings / recueil de communications" },
    { value: "NOTICE", label: "Notice" },
    { value: "ISSUE", label: "Numéro spécial / dossier de revue" },
    { value: "SOFTWARE", label: "Logiciel" },
    { value: "TRAD", label: "Traduction" },
    { value: "SON", label: "Document sonore" },
    { value: "MAP", label: "Carte" },
  ]},
  { name: "domain",       label: "Discipline",    type: "_domain"},
  { name: "submitType_s",         label: "Type de dépôt",  type: "_s", options: [ 
    { value: "file", label: "avec fichier" },
    { value: "notice", label: "notice" },
    { value: "annex", label: "annexe" },
  ]},
  { name: "language_s",           label: "Langue",        type: "_s",  options: [
    { value: "fr", label: "Français" },
    { value: "en", label: "Anglais" },
    { value: "de", label: "Allemand" },
    { value: "es", label: "Espagnol" },
    { value: "it", label: "Italien" },
    { value: "pt", label: "Portugais" },
    { value: "ru", label: "Russe" },
    { value: "zh", label: "Chinois" },
    { value: "ja", label: "Japonais" },
    { value: "ar", label: "Arabe" },
    { value: "ca", label: "Catalan" },
    {  value: "pl", label: "Polonais" },
    { value: "el", label: "Grec" },
    { value: "eu", label: "Basque" },
    { value: "ro", label: "Roumain" },
    { value: "nl", label: "Néerlandais" },
    { value: "tr", label: "Turc" },
    { value: "uk", label: "Ukrainien" },
    { value: "hy", label: "Arménien" },
    { value: "cs", label: "Tchèque" },
    { value: "ko", label: "Coréen" },
    { value: "fa", label: "Persan" },
    { value: "bg", label: "Bulgare" },
    { value: "ie", label: "Interlingue" },
    { value: "hu", label: "Hongrois" },
    { value: "vi", label: "Vietnamien" },
    { value: "br", label: "Breton" },
    { value: "oc", label: "Occitan" },
    { value: "la", label: "Latin" },
    { value: "sv", label: "Suédois" },
    { value: "id", label: "Indonésien" },
    { value: "da", label: "Danois" },
    { value: "eo", label: "Espéranto" },
    { value: "sa", label: "Sanskrit" },
    { value: "sr", label: "Serbe" },
    { value: "ta", label: "Tamoul" },
    { value: "sq", label: "Albanais" },
    { value: "hr", label: "Croate" },
    { value: "he", label: "Hébreu" },
    { value: "fi", label: "Finnois" },
    { value: "hi", label: "Hindi" },
    { value: "ur", label: "Ourdou" },
    { value: "mr", label: "Marathi" },
    { value: "ms", label: "Malais" },
    { value: "sk", label: "Slovaque" },
    { value: "ff", label: "Peul" },
    { value: "co", label: "Corse" },
    { value: "gl", label: "Galicien" },
    { value: "no", label: "Norvégien" },
    { value: "sl", label: "Slovène" },
    { value: "lt", label: "Lituanien" },
    { value: "bs", label: "Bosnien" },
    { value: "mg", label: "Malgache" },
    { value: "et", label: "Estonien" },
    { value: "sw", label: "Swahili" },
    { value: "az", label: "Azéri" },
    { value: "km", label: "Khmer" },
    { value: "lv", label: "Letton" },
    { value: "mk", label: "Macédonien" },
  ] },
  { name: "journalTitle_t",       label: "Titre de revue", type: "_t"     },
  { name: "anrProjectAcronym_s",       label: "Projet ANR (acronyme)", type: "_s"     },
  { name: "anrProjectReference_s",       label: "Projet ANR (ANR-01-ABC...)", type: "_s"     },
  { name: "audience_s",       label: "Audience", type: "_s", options: [
    { value: "1", label: "Non-spécifiée" },
    { value: "2", label: "Internationale" },  
    { value: "3", label: "Nationale" },
  ] },
  { name: "authEmailDomain_s",       label: "Domaine mail (sans @)", type: "_s"     },
  { name: "arxivId_s",       label: "Id ArXiv", type: "_s"     },
  { name: "bookTitle_t",       label: "Titre de l'ouvrage", type: "_t"     },
  { name: "director_t",       label: "Directeur de thèse", type: "_t"     },
  { name: "funding_t",       label: "Financement (texte libre)", type: "_t"     },
  { name: "halId_s",       label: "Hal ID", type: "_s"     },
  { name: "inPress_bool",       label: "À paraître", type: "_bool"     },  
  { name: "isbn_s",       label: "ISBN", type: "_s"     },
  { name: "issue_s",       label: "Volume", type: "_s"     },
  { name: "journalIssn_s",       label: "ISSN", type: "_s"     },
];
  

// Champs disponibles pour les facettes (on peut en ajouter d'autres ici)
const FACET_FIELD_SUGGESTIONS = [
  "authFullName_s",
  "collection_t",
  "docType_s",
  "primaryDomain_s",
  "publicationDateY_i",
  "submitType_s",
  "language_s",
  "journalTitle_s",
];

function getField(name) {
  return FIELDS.find(f => f.name === name);
}

function getOperators(fieldName) {
  const field = getField(fieldName);
  return field ? OPERATORS_BY_TYPE[field.type] : [];
}
